# Generated by Django 3.2.5 on 2022-01-15 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='pub_date',
        ),
    ]
